Models/Meetinginfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class Meetinginfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }
        public int NumberOfPeople { get; set; }
    }
}

Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public static class Repository
    {
        private static List<UserInfo> _users = new();

        //el ile bazı kayıtları yaptım
        static Repository(){
            _users.Add(new UserInfo() {Id=1, Name = "Kotan", Email = "kotan@gmail.com", Phone = "12121112" , WillAttend = true});
            _users.Add(new UserInfo() {Id=2, Name = "Selamet", Email = "selamet@gmail.com", Phone = "12121112" , WillAttend = true});
            _users.Add(new UserInfo() {Id=3, Name = "Atahan", Email = "atahan@gmail.com", Phone = "12121112" , WillAttend = false});
        }
        
        //bilgilerin gönderilmesi
        public static List<UserInfo> Users{
            get{
                return _users;
            }
        }

        //yeni kayıtları ekleme
        public static void CreatUser(UserInfo user){
            user.Id = Users.Count + 1 ;
            _users.Add(user);
        }

        //listeleme bölümünde detay kısmında o kişinin bilgileri görünmesi lazım bunuda o kişinin idsi ile tutabilirim
        public static UserInfo? GetById(int id){
            return _users.FirstOrDefault(user => user.Id == id);
        }
    }
}

Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MeetingApp.Models
{
    public class UserInfo
    {
        /*
            bu kısmı formdan gelen bilgileri taghelper ile alıp kullanmak 
        */

        //apply.cshtml de "novalidate" yaparak hata mesajını kendim yazdım
        
        //Required yaparak kullanıcıya bu alan zorunlu olduğunu ve bir giriş yapmasını söylüyorum
        public int Id { get; set; }

        [Required(ErrorMessage ="Ad alanı zorunlu")] 
        public string? Name { get; set; }//null

        [Required(ErrorMessage ="Telefon alanı zorunlu")] 
        public string? Phone { get; set; }

        [Required(ErrorMessage ="Email alanı zorunlu")] 
        [EmailAddress(ErrorMessage ="Hatalı email")] //email formatında da olmasını kontrol et dedim
        public string? Email { get; set; }

        [Required(ErrorMessage ="Katılım durumunuzu belirtiniz.")] 
        public bool? WillAttend { get; set; }//true,false,null
    }
}

Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController: Controller {
        public IActionResult Index(){
            //localhost
            //localhost/home
            //localhost/home/index

            
            //dinamik veri yollama
            int clock = DateTime.Now.Hour;
            // var helloo = clock > 12 ? "İyi Günler":"Günaydın";
            // return View(model: helloo);

            //viewBag-viewData
            // ViewBag.helloo = clock > 12 ? "İyi Günler":"Günaydın";
            //bu yolla sayfada direk erişebilir

            // ViewBag.UserName = "Mert";

            ViewData["hello"] = clock > 12 ? "İyi Günler":"Günaydın";

            int UserCount = Repository.Users.Where(info=>info.WillAttend == true).Count(); //katılımcı sayısını eklemek için

            // ViewData["UserName"]= "Mert";

            var meetinginfo = new Meetinginfo(){
                Id = 1,
                Location = "İstanbul, Abc Kongre Merkezi",
                Date = new DateTime(2024,01,20,20,0,0),
                NumberOfPeople = UserCount
            };

            return View(meetinginfo);
        }
    }
}

Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace MeetingApp.Controllers
{
   
    public class MeetingController : Controller
    {
    
        // [HttpGet] Thanks.cshtml yaptım burdan artık direk erişim değilde katıldığında direk o sayfaya gitsin o sayfada return View("Thanks",model); ile direk gidecek
        // public IActionResult Index()
        // {
        //     return View();
        // }

        //[HttpGet] =>getrequest yazmasakta çalısır
        [HttpGet]
        public IActionResult Apply(){//toplantıya katılım formu
            return View();
        }

        [HttpPost] //formdan aldığım bilgileri tekrardan alıp kullanmak için

        //public IActionResult Apply(string Name, string Phone, string Email, bool WillAttend) bunun yerine şimdi taghelper ile metot oluşturup direk listeyi çekicem:UserInfo ==>ModelBinding
        public IActionResult Apply(UserInfo model){
            //bu bilgileri burda database ya da liste ile ekleyebilirim şimfdilik bunları model içinde repositroy.cs içine aldım

            //Required yaparak kullanıcıya bu alan zorunlu olduğunu ve bir giriş yapmasını söylüyorum
            if(ModelState.IsValid){
                Repository.CreatUser(model);

                //katılan kişi sayısını almak için burdan katılanların sayısını alıcam
                ViewBag.UserCount = Repository.Users.Where(info=>info.WillAttend == true).Count();
                return View("Thanks",model);
            }else{
                return View(model);//önceki hatalı girişleri görsün diye modeli ekledim
            }

            
        }

        [HttpGet]
        public IActionResult List(){
            return View(Repository.Users);//kayıtlı kişileri listede göstermek için ekledim
        }

        //meeting/details/id(1,2,3...)
        public IActionResult Details(int id){
            return View(Repository.GetById(id));
        }
    }
}

Views/Home/index.cshtml
<!--
model string => viewBag ile direk göderdim
-viewbag at işareti var
<h1 class="h4">ViewBag.helloo, ViewBag.UserName</h1>
-->
<!--burda farklı bir tasarım yapmak istersem diğer sayfalardan ayrı bir layout oluşturdum onu aktif ettm veya null diyip de yapabilirim-->
@model Meetinginfo;
@{
    Layout = "_Layout2";
    ViewBag.Title = "Toplantı Başvuru";
}
<main class="text-center">
    <!-- <h1 class="h4">@ViewData["hello"], @ViewData["UserName"]</h1> -->
    <h1 class="h4">@ViewData["hello"]</h1><!--saat bilgisine göre yazacak-->
    <p>Toplantı katılım durumunuzu bildiriniz.</p>
    <!-- link yerine tagHelper kullanarak daha dinamik bir şeklide linke gidebilirim _Viewimports.cshtml eklemeleri yaptıktan sonra
        <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Yap</a>
    -->
    <div class="card my-2">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">@Model.Location</li>
            <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") tarihinde gerçekleşecek</li>
            <li class="list-group-item">@Model.NumberOfPeople Katılımcı</li>
        </ul>
    </div>

    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Başvuru Yap</a>
</main>

Views/Meeting/Apply.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Formu";
}
<h1 class="h4 text-center">Toplantı Katılım Formu</h1>
<form method="post" action="/Meeting/Apply" novalidate>
    <div asp-validation-summary="All"></div><!--Required yani eğer o alan büşsa hata mesajı için
    css kodlarını ise wwwrootaltında css/styles.css içinde
    -->
    <div class="mb-3">
        <!--
            <label for="Name" class="for-label">Ad Soyad</label>
            <input type="text" name="Name" id="Name" class="form-control">
             burada ki for yerine taghelper metotlarını kullanıp direk bilgileri alıcam

             meetngcontrollerda eklediğim post ile almak yerine taghelper kullandım
             [HttpPost] //formdan aldığım bilgileri tekrardan alıp kullanmak için
            public IActionResult Apply(string Name, string Phone, string Email, bool WillAttend){//toplantıya katılım formu
            Console.WriteLine(Name);
            Console.WriteLine(Email);
            Console.WriteLine(Phone);
            Console.WriteLine(WillAttend);
            return View();

        }

        -->
        <label asp-for="Name" class="for-label">Ad Soyad</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone" class="for-label">Telefon</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="for-label">Eposta</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend" class="for-label">Katılım Durumu</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Seçiniz</option>
            <option value="true">Evet, Geliyorum</option>
            <option value="false">Hayır, Gelmiyorum</option>
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo

@{
    ViewBag.Title = "Başvuru Detayı";
}

@{
    var clasName = @Model.WillAttend == true ? "primary":"danger";
}

<main class="text-center">
    <h1>Başvuru Detayı</h1>
    <p>
        <span class="badge text-bg-@clasName">
            @if(Model.WillAttend == true){
                <text>Katılıyor</text>
            }else{
                <text>Katılmıyor</text>
            }
        </span>
    </p>
    <p>İsim: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Telefon: @Model.Phone</p>
    <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@clasName">Katılımcı Listesi</a>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
@{
    ViewBag.Title = "Toplantı Katılım Listesi";
}
<main class="text-center">
    <h1 class="h4">Toplantı Katılım Listesi</h1>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Ad-Soyad</td>
                <td>Katılım Durumu</td>
                <td></td>
            </tr>
        </thead>
        <tbody>

            @{int i = 0; } <!--katılımcı sayısını tutmak için-->

            @foreach(var user in Model){

                var durum = user.WillAttend == true ? "Evet":"Hayır";

                var clasName = user.WillAttend == true ? "table-success":"table-danger";

                if(user.WillAttend == true){
                    i++;
                }

                <tr class="@clasName">
                    <td>@user.Name</td>
                    <td>@durum</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
                    </td>
                </tr>
            }
            
        </tbody>
    </table>

    <div class="card">
        <div class="card-body">
            <span>Katılımcı Sayısı: @i</span>
        </div>
    </div>
</main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
    ViewBag.Title = "Başvuru Durumu";
}
<main class="text-center">
    <h1 class="h4">Başvuru Durumu</h1>

    @if(Model.WillAttend == true){
        <!--toplantıya katılırsa bu sayfa görünsün-->

        <p>Teşekkürler,@Model.Name toplantıya sizinle birlikte @ViewBag.UserCount kişi katılıyor.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>

    } else{
        <p>@Model.Name , katılmadığından dolayı üzgünüz.</p>
        <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Formu</a>
    }
    
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--bootstrap kütüphanesini link yerine projeye indirip klasörün içinden aktif ettim
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" />
    -->
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/styles.css" />
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-primary text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-danger text-white p-2 text-center">
        MeetingApp
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>